### ISSUE TITLE
Can't add tags in comments? ☠

### ISSUE THREAD

**Issue by FrancesCoronel** [cornelltech/unicornucopia-issue-tracker#32]
Something broke when I tried adding tags in comment section of my idea because I forgot to add tags the first time around. rip ☠

![screenshot 2016-08-31 17 57 48](https://cloud.githubusercontent.com/assets/4284691/18147848/76eec6e6-6fa4-11e6-973c-f08c4addace0.png)

**Comment by AVatch** [comment]
hmm, yes some ppl are experiencing this will look more into it. thanks!

**Comment by AVatch** [comment]
The issue was adding more than 1 tags. it should be fixed, but re-open it if it persists. Thanks!
