### ISSUE TITLE
Tab for autocomplete name entry

### ISSUE THREAD

**Issue by oatsandsugar** [cornelltech/unicornucopia-issue-tracker#37]
when adding a co-ideator to an idea - autocomplete appears. To make it simpler to add more, have hitting tab select and insert the first listed autocomplete suggested name. (am I making sense here?)

**Comment by AVatch** [comment]
we are doing the select method atm so lets see how it feels.

**Comment by oatsandsugar** [comment]
Select is awkward for scrolling..
