### ISSUE TITLE
Adding new ideas is broken on desktop (OSX, Chrome)

### ISSUE THREAD

**Issue by aw729** [cornelltech/unicornucopia-issue-tracker#39]

**Comment by Dobes75** [comment]
![image](https://cloud.githubusercontent.com/assets/21957076/18210060/becb3024-7104-11e6-875c-63c6e60e8fc1.png)

This is the error message I get. I'm on Windows 7, Chrome.

**Comment by AVatch** [comment]
can you try it again?

**Comment by Dobes75** [comment]
Works again for me!

**Comment by Dobes75** [comment]
Works now!!

:: Andrew Doberstein
:: 603-769-1552

On Fri, Sep 2, 2016 at 12:13 PM, Adrian Vatchinsky <notifications@github.com
