### ISSUE TITLE
I am unable to view the comments on my ideas when I receive an email notification. 

### ISSUE THREAD

**Issue by sings257** [cornelltech/unicornucopia-issue-tracker#53]

**Comment by bruce401** [comment]
No way to access idea that a notification is referring to. Email/notification  icon both lead to 404 not found

**Comment by grutt** [comment]
its the trailing backslash 
ie.
https://www.unicornucopia.org/ideas/869/
should be
https://www.unicornucopia.org/ideas/869

maybe its a feature of the safe redirect of sendgrid which seems to be used?

**Comment by AVatch** [comment]
yup it was the trailing backslash o.O this is fixed but re-open if it persists
