### ISSUE TITLE
Unicornucopia API

### ISSUE THREAD

**Issue by omris1** [cornelltech/unicornucopia-issue-tracker#61]
Seeing as the two main idea exploration methods (currently) are reverse chronological sweep and search (which is not intuitive) could be interesting to open up an API to access data about the ideas. This could allow us to learn what are the attributes of successful ideas...

**Comment by AVatch** [comment]
Thanks - we've added some basic sorts. we have plans for making the API available however it is a bit down the line on the roadmap so that we can ensure it will work properly
