### ISSUE TITLE
Only added  3 of 5 collaborators

### ISSUE THREAD

**Issue by grutt** [cornelltech/unicornucopia-issue-tracker#62]
https://www.unicornucopia.org/ideas/1509

were not added...
Jonathon Shiff
Yiqing Xue

Chrome on ubuntu

**Comment by AVatch** [comment]
hmm ok - i'll add them to that idea. thanks for reporting

**Comment by AVatch** [comment]
can you confirm the list of creators is correct now?

**Comment by grutt** [comment]
yes, thanks
