### ISSUE TITLE
Notifications don't take you to the story, "something broke"

### ISSUE THREAD

**Issue by kanoria** [cornelltech/unicornucopia-issue-tracker#64]
Clicking a notification from the lightning bolt doesnt take you anywhere, disabling you to see what story people commented on or liked without having to go through all your ideas to find it.
<img width="839" alt="screenshot 2016-09-13 13 15 01" src="https://cloud.githubusercontent.com/assets/13887598/18483940/56ec469c-79b4-11e6-82d7-99167f2c50b7.png">

**Comment by AVatch** [comment]
it should take you there, reopen if it doesnt
